---
devices:
  multithreaded: true
  samplerate: 44100
  chunksize: 4096
  resampler:
    type: Synchronous
  capture_samplerate: 44100
  playback:
    type: File
    filename: "/dev/null"
    channels: 60
    format: FLOAT32LE
  capture:
    type: CoreAudio
    device: "BlackHole 2ch"
    channels: 2
    format: FLOAT32LE
filters:
  band_0:
    type: Biquad
    parameters:
      type: Lowpass
      freq: 25
      q: 1.0
  band_1:
    type: Biquad
    parameters:
      type: Bandpass
      freq: 31.5
      q: 4.5
  band_2:
    type: Biquad
    parameters:
      type: Bandpass
      freq: 40
      q: 4.5
  band_3:
    type: Biquad
    parameters:
      type: Bandpass
      freq: 50
      q: 4.5
  band_4:
    type: Biquad
    parameters:
      type: Bandpass
      freq: 63
      q: 4.5
  band_5:
    type: Biquad
    parameters:
      type: Bandpass
      freq: 80
      q: 4.5
  band_6:
    type: Biquad
    parameters:
      type: Bandpass
      freq: 100
      q: 4.5
  band_7:
    type: Biquad
    parameters:
      type: Bandpass
      freq: 125
      q: 4.5
  band_8:
    type: Biquad
    parameters:
      type: Bandpass
      freq: 160
      q: 4.5
  band_9:
    type: Biquad
    parameters:
      type: Bandpass
      freq: 200
      q: 4.5
  band_10:
    type: Biquad
    parameters:
      type: Bandpass
      freq: 250
      q: 4.5
  band_11:
    type: Biquad
    parameters:
      type: Bandpass
      freq: 315
      q: 4.5
  band_12:
    type: Biquad
    parameters:
      type: Bandpass
      freq: 400
      q: 4.5
  band_13:
    type: Biquad
    parameters:
      type: Bandpass
      freq: 500
      q: 4.5
  band_14:
    type: Biquad
    parameters:
      type: Bandpass
      freq: 630
      q: 4.5
  band_15:
    type: Biquad
    parameters:
      type: Bandpass
      freq: 800
      q: 4.5
  band_16:
    type: Biquad
    parameters:
      type: Bandpass
      freq: 1000
      q: 4.5
  band_17:
    type: Biquad
    parameters:
      type: Bandpass
      freq: 1250
      q: 4.5
  band_18:
    type: Biquad
    parameters:
      type: Bandpass
      freq: 1600
      q: 4.5
  band_19:
    type: Biquad
    parameters:
      type: Bandpass
      freq: 2000
      q: 4.5
  band_20:
    type: Biquad
    parameters:
      type: Bandpass
      freq: 2500
      q: 4.5
  band_21:
    type: Biquad
    parameters:
      type: Bandpass
      freq: 3150
      q: 4.5
  band_22:
    type: Biquad
    parameters:
      type: Bandpass
      freq: 4000
      q: 4.5
  band_23:
    type: Biquad
    parameters:
      type: Bandpass
      freq: 5000
      q: 4.5
  band_24:
    type: Biquad
    parameters:
      type: Bandpass
      freq: 6300
      q: 4.5
  band_25:
    type: Biquad
    parameters:
      type: Bandpass
      freq: 8000
      q: 4.5
  band_26:
    type: Biquad
    parameters:
      type: Bandpass
      freq: 10000
      q: 4.5
  band_27:
    type: Biquad
    parameters:
      type: Bandpass
      freq: 12500
      q: 4.5
  band_28:
    type: Biquad
    parameters:
      type: Bandpass
      freq: 16000
      q: 4.5
  band_29:
    type: Biquad
    parameters:
      type: Bandpass
      freq: 20000
      q: 4.5

mixers:
  30band:
    channels:
      in: 2
      out: 60
    mapping:
      - dest: 0
        sources:
          - channel: 0
      - dest: 1
        sources:
          - channel: 1
      - dest: 2
        sources:
          - channel: 0
      - dest: 3
        sources:
          - channel: 1
      - dest: 4
        sources:
          - channel: 0
      - dest: 5
        sources:
          - channel: 1
      - dest: 6
        sources:
          - channel: 0
      - dest: 7
        sources:
          - channel: 1
      - dest: 8
        sources:
          - channel: 0
      - dest: 9
        sources:
          - channel: 1
      - dest: 10
        sources:
          - channel: 0
      - dest: 11
        sources:
          - channel: 1
      - dest: 12
        sources:
          - channel: 0
      - dest: 13
        sources:
          - channel: 1
      - dest: 14
        sources:
          - channel: 0
      - dest: 15
        sources:
          - channel: 1
      - dest: 16
        sources:
          - channel: 0
      - dest: 17
        sources:
          - channel: 1
      - dest: 18
        sources:
          - channel: 0
      - dest: 19
        sources:
          - channel: 1
      - dest: 20
        sources:
          - channel: 0
      - dest: 21
        sources:
          - channel: 1
      - dest: 22
        sources:
          - channel: 0
      - dest: 23
        sources:
          - channel: 1
      - dest: 24
        sources:
          - channel: 0
      - dest: 25
        sources:
          - channel: 1
      - dest: 26
        sources:
          - channel: 0
      - dest: 27
        sources:
          - channel: 1
      - dest: 28
        sources:
          - channel: 0
      - dest: 29
        sources:
          - channel: 1
      - dest: 30
        sources:
          - channel: 0
      - dest: 31
        sources:
          - channel: 1
      - dest: 32
        sources:
          - channel: 0
      - dest: 33
        sources:
          - channel: 1
      - dest: 34
        sources:
          - channel: 0
      - dest: 35
        sources:
          - channel: 1
      - dest: 36
        sources:
          - channel: 0
      - dest: 37
        sources:
          - channel: 1
      - dest: 38
        sources:
          - channel: 0
      - dest: 39
        sources:
          - channel: 1
      - dest: 40
        sources:
          - channel: 0
      - dest: 41
        sources:
          - channel: 1
      - dest: 42
        sources:
          - channel: 0
      - dest: 43
        sources:
          - channel: 1
      - dest: 44
        sources:
          - channel: 0
      - dest: 45
        sources:
          - channel: 1
      - dest: 46
        sources:
          - channel: 0
      - dest: 47
        sources:
          - channel: 1
      - dest: 48
        sources:
          - channel: 0
      - dest: 49
        sources:
          - channel: 1
      - dest: 50
        sources:
          - channel: 0
      - dest: 51
        sources:
          - channel: 1
      - dest: 52
        sources:
          - channel: 0
      - dest: 53
        sources:
          - channel: 1
      - dest: 54
        sources:
          - channel: 0
      - dest: 55
        sources:
          - channel: 1
      - dest: 56
        sources:
          - channel: 0
      - dest: 57
        sources:
          - channel: 1
      - dest: 58
        sources:
          - channel: 0
      - dest: 59
        sources:
          - channel: 1

pipeline:

  - type: Mixer
    name: 30band
  - type: Filter
    channels: [0, 1]
    names:
      - band_0
      - band_0
  - type: Filter
    channels: [2, 3]
    names:
      - band_1
      - band_1
  - type: Filter
    channels: [4, 5]
    names:
      - band_2
      - band_2
  - type: Filter
    channels: [6, 7]
    names:
      - band_3
      - band_3
  - type: Filter
    channels: [8, 9]
    names:
      - band_4
      - band_4
  - type: Filter
    channels: [10, 11]
    names:
      - band_5
      - band_5
  - type: Filter
    channels: [12, 13]
    names:
      - band_6
      - band_6
  - type: Filter
    channels: [14, 15]
    names:
      - band_7
      - band_7
  - type: Filter
    channels: [16, 17]
    names:
      - band_8
      - band_8
  - type: Filter
    channels: [18, 19]
    names:
      - band_9
      - band_9
  - type: Filter
    channels: [20, 21]
    names:
      - band_10
      - band_10
  - type: Filter
    channels: [22, 23]
    names:
      - band_11
      - band_11
  - type: Filter
    channels: [24, 25]
    names:
      - band_12
      - band_12
  - type: Filter
    channels: [26, 27]
    names:
      - band_13
      - band_13
  - type: Filter
    channels: [28, 29]
    names:
      - band_14
      - band_14
  - type: Filter
    channels: [30, 31]
    names:
      - band_15
      - band_15
  - type: Filter
    channels: [32, 33]
    names:
      - band_16
      - band_16
  - type: Filter
    channels: [34, 35]
    names:
      - band_17
      - band_17
  - type: Filter
    channels: [36, 37]
    names:
      - band_18
      - band_18
  - type: Filter
    channels: [38, 39]
    names:
      - band_19
      - band_19
  - type: Filter
    channels: [40, 41]
    names:
      - band_20
      - band_20
  - type: Filter
    channels: [42, 43]
    names:
      - band_21
      - band_21
  - type: Filter
    channels: [44, 45]
    names:
      - band_22
      - band_22
  - type: Filter
    channels: [46, 47]
    names:
      - band_23
      - band_23
  - type: Filter
    channels: [48, 49]
    names:
      - band_24
      - band_24
  - type: Filter
    channels: [50, 51]
    names:
      - band_25
      - band_25
  - type: Filter
    channels: [52, 53]
    names:
      - band_26
      - band_26
  - type: Filter
    channels: [54, 55]
    names:
      - band_27
      - band_27
  - type: Filter
    channels: [56, 57]
    names:
      - band_28
      - band_28
  - type: Filter
    channels: [58, 59]
    names:
      - band_29
      - band_29
