// CalibrationCurve parser tests — covering the REW, miniDSP UMIK,
// and bare-FRD format variants so the file picker can accept any of
// them without users having to massage the file by hand.

import Foundation
import Testing

@testable import DSPAudio
@testable import DSPMeasurement

@Suite struct CalibrationFileTests {

  /// REW-style: `* commented` header, space-separated data rows,
  /// magnitude only.
  @Test func REWFormatTwoColumn() throws {
    let text = """
      * Frequency Response Data
      * Generated by REW V5.20
      * Frequency [Hz]   Magnitude [dB]
      20.0   -3.5
      100.0  -1.0
      1000.0  0.0
      10000.0 -2.5
      """
    let curve = try CalibrationCurve.parse(text)
    #expect(curve.frequencies == [20.0, 100.0, 1000.0, 10000.0])
    #expect(curve.magnitudesDB == [-3.5, -1.0, 0.0, -2.5])
    #expect(curve.phasesDeg == nil)
  }

  /// REW-style with phase column.
  @Test func REWFormatThreeColumn() throws {
    let text = """
      * Frequency Response Data
      20.0   -3.5  -45.0
      100.0  -1.0  -10.0
      1000.0  0.0   0.0
      """
    let curve = try CalibrationCurve.parse(text)
    #expect(curve.phasesDeg == [-45.0, -10.0, 0.0])
  }

  /// miniDSP UMIK-1 calibration file. Quoted header line, no comment
  /// marker, then tab-separated rows.
  @Test func UMIKFormat() throws {
    let text =
      "\"Sens Factor =-1.6dB, SERNO: 9000123\"\n"
      + "10.000\t-3.5\n"
      + "12.500\t-3.2\n"
      + "20.000\t-1.8\n"
      + "1000.000\t0.0\n"
      + "20000.000\t-2.1\n"
    let curve = try CalibrationCurve.parse(text)
    #expect(curve.frequencies.count == 5)
    #expect(curve.frequencies[0] == 10.0)
    #expect(curve.frequencies[3] == 1000.0)
    #expect(curve.magnitudesDB[0] == -3.5)
    // Sens Factor header is skipped; no phase data.
    #expect(curve.phasesDeg == nil)
  }

  /// Log-frequency interpolation. Geometric midpoint should give
  /// the magnitude midpoint exactly.
  @Test func LogInterpolation() throws {
    let text = "100.0 0.0\n10000.0 12.0\n"
    let curve = try CalibrationCurve.parse(text)
    let geomMid = sqrt(100.0 * 10000.0)  // = 1000
    let v = curve.magnitude(at: geomMid)
    #expect(abs(v - 6.0) < 1e-9)
    // Outside range: clamp to nearest endpoint.
    #expect(curve.magnitude(at: 50.0) == 0.0)
    #expect(curve.magnitude(at: 50_000.0) == 12.0)
  }

  /// Sampling onto a log grid: returned array has the same length as
  /// the grid and matches per-point lookups.
  @Test func GridSampling() throws {
    let text = "100.0 0.0\n10000.0 6.0\n"
    let curve = try CalibrationCurve.parse(text)
    let grid: [Double] = [50, 100, 1000, 10000, 50000]
    let sampled = curve.sampledMagnitudeDB(at: grid)
    #expect(sampled.count == grid.count)
    #expect(sampled[1] == 0.0)  // exact endpoint
    #expect(abs(sampled[2] - 3.0) < 1e-9)  // log midpoint
    #expect(sampled[3] == 6.0)
    #expect(sampled[0] == 0.0)  // clamped
    #expect(sampled[4] == 6.0)  // clamped
  }

  /// Round-trip: write a curve, read it back, verify equivalence.
  @Test func RoundTripExportImport() throws {
    let original = CalibrationCurve(
      frequencies: [20.0, 100.0, 1000.0, 10000.0],
      magnitudesDB: [-3.5, -1.0, 0.0, -2.5],
      phasesDeg: [-45.0, -10.0, 0.0, -5.0])
    let tmp = FileManager.default.temporaryDirectory.appendingPathComponent(
      "cal-test-\(UUID().uuidString).frd")
    defer { try? FileManager.default.removeItem(at: tmp) }
    try original.writeFRD(to: tmp.path, comment: "Round-trip test")
    let reloaded = try CalibrationCurve.load(at: tmp.path)
    #expect(reloaded.frequencies == original.frequencies)
    for i in 0..<original.magnitudesDB.count {
      #expect(abs(reloaded.magnitudesDB[i] - original.magnitudesDB[i]) < 1e-6)
    }
    #expect(reloaded.phasesDeg != nil)
    if let p = reloaded.phasesDeg {
      for i in 0..<p.count {
        #expect(abs(p[i] - original.phasesDeg![i]) < 1e-6)
      }
    }
  }
}
